// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceAggregator.Infrastructure;

#nullable disable

namespace PriceAggregator.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceAggregator.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("TreeLevel")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "admin",
                            Name = "Shoes",
                            ParentId = 0,
                            TreeLevel = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "admin",
                            Name = "Womens Shoes",
                            ParentId = 1,
                            TreeLevel = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "admin",
                            Name = "Mens Shoes",
                            ParentId = 1,
                            TreeLevel = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "admin",
                            Name = "Shirts",
                            ParentId = 0,
                            TreeLevel = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "admin",
                            Name = "Womens Shirts",
                            ParentId = 3,
                            TreeLevel = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "admin",
                            Name = "Mens Shirts",
                            ParentId = 3,
                            TreeLevel = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "admin",
                            Name = "Jackets",
                            ParentId = 0,
                            TreeLevel = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "admin",
                            Name = "Gaming",
                            ParentId = 0,
                            TreeLevel = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "admin",
                            Name = "Smartphones",
                            ParentId = 0,
                            TreeLevel = 0
                        });
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("StoreId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedBy = "admin",
                            Name = "ADIDAS",
                            Price = 79.98m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/Nike-Blazer-Jumbo-DN2158-White/dp/B09Q91N4Q7"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedBy = "admin",
                            Name = "NIKE",
                            Price = 180.00m,
                            PriceUnit = "$",
                            StoreId = 2,
                            Url = "https://www.stirlingsports.co.nz/new/blazer-low-77-jumbo-mens-dn2158-101"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedBy = "admin",
                            Name = "ZEN",
                            Price = 100.00m,
                            PriceUnit = "$",
                            StoreId = 2,
                            Url = "https://www.stirlingsports.co.nz/mens/clothing/tees-and-singlets/IL5172/Adventure-Volcano-Long-Sleeve-Tee.html"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            CreatedBy = "admin",
                            Name = "PUMA",
                            Price = 70.00m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/Volcano-Adventure-Climate-Premium-T-Shirt/dp/B0BH88FLPM?customId=B0753883B1&customizationToken=MC_Assembly_1%23B0753883B1&th=1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CreatedBy = "admin",
                            Name = "HENI",
                            Price = 879.00m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/GIGABYTE-G5-1920x1080-i5-12500H-KF-E3US333SH/dp/B0BVRGF3MR/ref=sr_1_8?keywords=gigabyte&qid=1694092757&s=pc&sprefix=gigabyte%2Caps%2C190&sr=1-8"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            CreatedBy = "admin",
                            Name = "ASUS",
                            Price = 879.00m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/GIGABYTE-G5-1920x1080-i5-12500H-KF-E3US333SH/dp/B0BVRGF3MR/ref=sr_1_8?keywords=gigabyte&qid=1694092757&s=pc&sprefix=gigabyte%2Caps%2C190&sr=1-8"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            CreatedBy = "admin",
                            Name = "HP",
                            Price = 7287.15m,
                            PriceUnit = "$",
                            StoreId = 3,
                            Url = "https://www.bestbuy.ca/en-ca/product/custom-gigabyte-aorus-15-laptop-intel-i7-12700h-32gb-ram-4tb-pcie-ssd-nvidia-rtx-3070-ti-15-6-win-10-pro/15997948"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            CreatedBy = "admin",
                            ImagePath = "https://cdn.mos.cms.futurecdn.net/yDn3ZSXu9eSBxmXQDZ4PCF-650-80.jpg.webp",
                            Name = "IPhone 15",
                            Price = 729.99m,
                            PriceUnit = "$",
                            StoreId = 3,
                            Url = "https://www.bestbuy.com/site/apple-iphone-15-128gb-blue-at-t/6417993.p?skuId=6417993"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedBy = "admin",
                            ImagePath = "https://cdn.mos.cms.futurecdn.net/yDn3ZSXu9eSBxmXQDZ4PCF-650-80.jpg.webp",
                            Name = "IPhone 15",
                            Price = 720m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.fr/Apple-iPhone-15-128-Go/dp/B0CHXFCYCR?language=en_GB"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 9,
                            CreatedBy = "admin",
                            ImagePath = "https://cdn.mos.cms.futurecdn.net/yDn3ZSXu9eSBxmXQDZ4PCF-650-80.jpg.webp",
                            Name = "IPhone 15",
                            Price = 709m,
                            PriceUnit = "$",
                            StoreId = 4,
                            Url = "https://www.amazon.fr/Apple-iPhone-15-128-Go/dp/B0CHXFCYCR?language=en_GB"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 9,
                            CreatedBy = "admin",
                            ImagePath = "https://www.samsungshop.tn/26760-large_default/galaxy-s24-ultra-prix-tunisie.jpg",
                            Name = "Samsung 24 Ultra",
                            Price = 1012.14m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/SAMSUNG-Smartphone-Unlocked-Android-Titanium/dp/B0CMDM65JH"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 9,
                            CreatedBy = "admin",
                            ImagePath = "https://www.samsungshop.tn/26760-large_default/galaxy-s24-ultra-prix-tunisie.jpg",
                            Name = "Samsung 24 Ultra",
                            Price = 1091.99m,
                            PriceUnit = "$",
                            StoreId = 3,
                            Url = "https://www.bestbuy.com/site/samsung-galaxy-s24-ultra-512gb-unlocked-titanium-black/6569875.p?skuId=6569875"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 9,
                            CreatedBy = "admin",
                            ImagePath = "https://www.samsungshop.tn/26760-large_default/galaxy-s24-ultra-prix-tunisie.jpg",
                            Name = "Samsung 24 Ultra",
                            Price = 960.61m,
                            PriceUnit = "$",
                            StoreId = 4,
                            Url = "https://www.aliexpress.com/item/1005006524667199.html"
                        });
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("IconPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "admin",
                            IconPath = "PlaceholderPath",
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "admin",
                            IconPath = "PlaceholderPath",
                            Name = "Stirling Sports"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "admin",
                            IconPath = "PlaceholderPath",
                            Name = "BestBuy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "admin",
                            IconPath = "PlaceholderPath",
                            Name = "AliExpress"
                        });
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Category", b =>
                {
                    b.HasOne("PriceAggregator.Core.Entities.Feature", "Feature")
                        .WithMany("Categories")
                        .HasForeignKey("FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Product", b =>
                {
                    b.HasOne("PriceAggregator.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceAggregator.Core.Entities.Feature", "Feature")
                        .WithMany("Products")
                        .HasForeignKey("FeatureId");

                    b.HasOne("PriceAggregator.Core.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Feature");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Store", b =>
                {
                    b.HasOne("PriceAggregator.Core.Entities.Feature", "Feature")
                        .WithMany("Stores")
                        .HasForeignKey("FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Feature", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");

                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
