// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceAggregator.Infrastructure;

#nullable disable

namespace PriceAggregator.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceAggregator.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("TreeLevel")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "admin",
                            Name = "Shoes",
                            ParentId = 0,
                            TreeLevel = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "admin",
                            Name = "Womens Shoes",
                            ParentId = 1,
                            TreeLevel = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "admin",
                            Name = "Mens Shoes",
                            ParentId = 1,
                            TreeLevel = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "admin",
                            Name = "Shirts",
                            ParentId = 0,
                            TreeLevel = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "admin",
                            Name = "Womens Shirts",
                            ParentId = 3,
                            TreeLevel = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "admin",
                            Name = "Mens Shirts",
                            ParentId = 3,
                            TreeLevel = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "admin",
                            Name = "Jackets",
                            ParentId = 0,
                            TreeLevel = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "admin",
                            Name = "Gaming",
                            ParentId = 0,
                            TreeLevel = 0
                        });
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatrgoryID")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatrgoryID");

                    b.HasIndex("StoreId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatrgoryID = 2,
                            CreatedBy = "admin",
                            Name = "ADIDAS",
                            Price = 79.98m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/Nike-Blazer-Jumbo-DN2158-White/dp/B09Q91N4Q7"
                        },
                        new
                        {
                            Id = 2,
                            CatrgoryID = 3,
                            CreatedBy = "admin",
                            Name = "NIKE",
                            Price = 180.00m,
                            PriceUnit = "$",
                            StoreId = 2,
                            Url = "https://www.stirlingsports.co.nz/new/blazer-low-77-jumbo-mens-dn2158-101"
                        },
                        new
                        {
                            Id = 3,
                            CatrgoryID = 5,
                            CreatedBy = "admin",
                            Name = "ZEN",
                            Price = 100.00m,
                            PriceUnit = "$",
                            StoreId = 2,
                            Url = "https://www.stirlingsports.co.nz/mens/clothing/tees-and-singlets/IL5172/Adventure-Volcano-Long-Sleeve-Tee.html"
                        },
                        new
                        {
                            Id = 4,
                            CatrgoryID = 6,
                            CreatedBy = "admin",
                            Name = "PUMA",
                            Price = 70.00m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/Volcano-Adventure-Climate-Premium-T-Shirt/dp/B0BH88FLPM?customId=B0753883B1&customizationToken=MC_Assembly_1%23B0753883B1&th=1"
                        },
                        new
                        {
                            Id = 5,
                            CatrgoryID = 7,
                            CreatedBy = "admin",
                            Name = "HENI",
                            Price = 879.00m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/GIGABYTE-G5-1920x1080-i5-12500H-KF-E3US333SH/dp/B0BVRGF3MR/ref=sr_1_8?keywords=gigabyte&qid=1694092757&s=pc&sprefix=gigabyte%2Caps%2C190&sr=1-8"
                        },
                        new
                        {
                            Id = 6,
                            CatrgoryID = 8,
                            CreatedBy = "admin",
                            Name = "ASUS",
                            Price = 879.00m,
                            PriceUnit = "$",
                            StoreId = 1,
                            Url = "https://www.amazon.com/GIGABYTE-G5-1920x1080-i5-12500H-KF-E3US333SH/dp/B0BVRGF3MR/ref=sr_1_8?keywords=gigabyte&qid=1694092757&s=pc&sprefix=gigabyte%2Caps%2C190&sr=1-8"
                        },
                        new
                        {
                            Id = 7,
                            CatrgoryID = 8,
                            CreatedBy = "admin",
                            Name = "HP",
                            Price = 7287.15m,
                            PriceUnit = "$",
                            StoreId = 3,
                            Url = "https://www.bestbuy.ca/en-ca/product/custom-gigabyte-aorus-15-laptop-intel-i7-12700h-32gb-ram-4tb-pcie-ssd-nvidia-rtx-3070-ti-15-6-win-10-pro/15997948"
                        });
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "admin",
                            IconPath = "PlaceholderPath",
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "admin",
                            IconPath = "PlaceholderPath",
                            Name = "Stirling Sports"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "admin",
                            IconPath = "PlaceholderPath",
                            Name = "BestBuy"
                        });
                });

            modelBuilder.Entity("PriceAggregator.Core.Entities.Product", b =>
                {
                    b.HasOne("PriceAggregator.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CatrgoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceAggregator.Core.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });
#pragma warning restore 612, 618
        }
    }
}
